name: Step 1, Create a branch

# This step listens for the learner to create branch `my-first-branch`.
# This workflow updates from step 1 to step 2.

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the branch to create'
        required: true
        default: 'my-first-branch'
  create:

permissions:
  contents: write  # Allows the workflow to create and modify content in the repository

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: get_step
        run: |
          echo "current_step=$(cat .github/steps/-step.txt)" >> $GITHUB_ENV

  on_create_a_branch:
    name: On create a branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new branch
        run: |
          git checkout -b my-first-branch
          git push origin my-first-branch

      - name: Create a sample file
        run: |
          echo "This is a sample file created automatically." > sample.txt
          git add sample.txt
          git commit -m "Added a sample file"
          git push origin my-first-branch
